travis:
  secure:
    BINSTAR_TOKEN: Ew4Sa8AY1LtTxrg0S+0h45aVqAncip//oV9qkAxJlxLFunfS+tQTAeuzg09UU+0A/3KMXPSZJnGJG3iuTqImn1jcpUvhD7xACD1Mk/uc+KpUtz5t91tp94reD+9TiPQ9q0JxacxD0zOm6opn4ckuuijS3sKYBj+bnyb1x4OGJ6wXkSk9+y2Sxn4fiA72xjyRjdgF7V8yGIbvYrVAVycch66fdstub+6p6iIHWaGuvdAA4PZkCkB6bnv/7xoxSyrGC8wuU00Uah0MD3Km/YfdnYbS+D+Lj/0mwfxFadomwJtgpID0g2DLcfqzpPe+iJcJDuUZHR98/8GvxraQ+ofioip50Kp+603il+BDiftWvYlL35znvJPljsM/KERJi5RSmE3vjfXvmDnfSIItoCFcObdAfqlTUeHJWhNdqtDk68WRNX1OCWONGkR6p5dAJFhZj5zA1yQ+tIyEhd06k/AYTkXXgFka0nBKdhFrdHNhYy9KZUJORY/q+xs+fXnSGGV4AtCs/+QwttZOF8iKMyECTlAwkh0HdwtAL6X/JBcJg2CmuZDDJxPHcSz7FVy3PG0Tuc9RUl8du4tkFHXbw8ZSLSO7YTMUbTrQdEbacDJMPT/3eiH8DhZ1d1y1pi8l/rs36VJOPxyttPfeJn/yhZweGyWM2pc9gZ32kfrGHQK433w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
