appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: nUfBfgqIoV3zFCrxIVfVLlWIvjEiAMcnOmBjsZnJZ2QFYU/ZYj3ea1QjGSdPmU0Im/eihSnrioB3qKD4qvYhn4lOf6Ztm9tNUsRU9kIuIVusa7qowwtyBE5ZFKYMp3hTaKfAvPKG5SndnkBxUGKV2T+1rs7gv1d0pX0+8R6kXQrHjOPBSPAKA891UCIkL8h88Fq3dxVeuzq222cHqunmW4eWtvPHVLfP55DFyP8i+8Gt1C8BZk7DYNDLC24uhr8ym4OCO4Zp6Z9FkcMjmsasAXz+BOPeiw5e6wcTUQM9HD/kjqKz672EehI46egIkqtpHcCtK43kVd54ELRX4MF2wVHRk35xWhMKURprBW3sRkrD4Gy9x+5/W7zEUZF6v05xVjpHXs1uU+wik1qSJzMpDVo5C0rVBChZQaHiNerr59PTB2AJniYMmlHQ+1kFNbwFt383FcP98K085Lwm7PxCwRZ0DT3ONUBkBG8LB4bvQPIyZYaEPA/Gdape59dsorNFH9xPEwhgJ9dsntc7Sbe9jrfmFrT+bdMXqAsvs4xzX0oxKltwS8UIECXsf1fj1bdiVoujdltooEJWwFUd5v8NihSSL9PyvE09R0qxM+noFX9q0F1pKVT6rJn7vGe0KR+z3B8Obv5p5YsdHZNK8ZJjz4pT/0pgm3r2JIO5+2S/bUY=
